package com.bortbort.arduino.FiloFirmata;

import com.bortbort.arduino.FiloFirmata.PortAdapters.*;

/**
 * Created by chuck on 1/4/2016.
 */
public class FirmataConfiguration {
    // Anything added here must also be added to:
    // Constructor method "protected FirmataConfiguration(FirmataConfiguration configuration)"
    // String method "public String toString()"
    private String serialPortID = "COM3";
    private Integer serialPortBaudRate = 57600;
    private SerialPortDataBits serialPortDataBits = SerialPortDataBits.DATABITS_8;
    private SerialPortStopBits serialPortStopBits = SerialPortStopBits.STOPBITS_1;
    private SerialPortParity serialPortParity = SerialPortParity.PARITY_NONE;
    private Class<? extends SerialPort> serialPortAdapterClass = PureJavaCommSerialPort.class;


    public FirmataConfiguration(String serialPortID) {
        this.serialPortID = serialPortID;
    }

    public FirmataConfiguration(Integer serialPortBaudRate) {
        this.serialPortBaudRate = serialPortBaudRate;
    }

    public FirmataConfiguration(String serialPortID, Integer serialPortBaudRate) {
        this.serialPortID = serialPortID;
        this.serialPortBaudRate = serialPortBaudRate;
    }

    public FirmataConfiguration() {
    }

    // Configuration cloning
    protected FirmataConfiguration(FirmataConfiguration configuration) {
        serialPortID = configuration.serialPortID;
        serialPortBaudRate = configuration.serialPortBaudRate;
        serialPortDataBits = configuration.serialPortDataBits;
        serialPortStopBits = configuration.serialPortStopBits;
        serialPortParity = configuration.serialPortParity;
        serialPortAdapterClass = configuration.serialPortAdapterClass;
    }


    public String getSerialPortID() {
        return serialPortID;
    }

    public void setSerialPortID(String serialPortID) {
        this.serialPortID = serialPortID;
    }

    public Integer getSerialPortBaudRate() {
        return serialPortBaudRate;
    }

    public void setSerialPortBaudRate(Integer serialPortBaudRate) {
        this.serialPortBaudRate = serialPortBaudRate;
    }

    public SerialPortDataBits getSerialPortDataBits() {
        return serialPortDataBits;
    }

    public void setSerialPortDataBits(SerialPortDataBits serialPortDataBits) {
        this.serialPortDataBits = serialPortDataBits;
    }

    public SerialPortStopBits getSerialPortStopBits() {
        return serialPortStopBits;
    }

    public void setSerialPortStopBits(SerialPortStopBits serialPortStopBits) {
        this.serialPortStopBits = serialPortStopBits;
    }

    public SerialPortParity getSerialPortParity() {
        return serialPortParity;
    }

    public void setSerialPortParity(SerialPortParity serialPortParity) {
        this.serialPortParity = serialPortParity;
    }

    public Class<? extends SerialPort> getSerialPortAdapterClass() {
        return serialPortAdapterClass;
    }

    public void setSerialPortAdapterClass(Class<? extends SerialPort> serialPortAdapterClass) {
        this.serialPortAdapterClass = serialPortAdapterClass;
    }


    // Auto generated by IDEA
    @Override
    public String toString() {
        return "FirmataConfiguration{" +
                "serialPortID='" + serialPortID + '\'' +
                ", serialPortBaudRate=" + serialPortBaudRate +
                ", serialPortDataBits=" + serialPortDataBits +
                ", serialPortStopBits=" + serialPortStopBits +
                ", serialPortParity=" + serialPortParity +
                ", serialPortAdapterClass=" + serialPortAdapterClass.getName() +
                '}';
    }
}
